### ISSUE TITLE
Questions about reproducing

### ISSUE THREAD

**Issue by 1chizhang** [hminle/gamut-mlp#1]
Hi, really nice work. I want to reproduce the results you have in your paper. Would you mind writing a little more detailed tutorial, like links to the training test set, and the commands for training? Thanks！

**Comment by hminle** [comment]
Hi @Volodymyr233 , thank you so much. I am working on it. I will upload the full dataset and write a detailed tutorial how to install and run the code.

**Comment by hminle** [comment]
@Volodymyr233 Hi, you can check out the README.md for more details. 
I will add more examples

**Comment by 1chizhang** [comment]
Thanks!!!!
