### ISSUE TITLE
How to use it if i have an sRGB image?

### ISSUE THREAD

**Issue by shuwei666** [hminle/gamut-mlp#2]
Great work!

My question is, suppose I have an image in the sRGB color space, can I directly apply the parameters derived from your training to recover the image to ProPhoto space?
 
Or does your model only apply to scenarios where you have both wide-gamut and sRGB scenes simultaneously?

**Comment by hminle** [comment]
Hi @shuwei666 , this paper is about the whole framework, you need to have both wide-gamut and small-gamut images.
In the case, you only have small gamut images like sRGB, you can try our another paper, which trains the bigger deep network to recover wide-gamut values: [GamutNet](https://github.com/gamut-mapping/GamutNet)

**Comment by shuwei666** [comment]
Thanks!

It looks like you have two stages, reduction and expansion. I have two more questions:

1. If I only have a single pair of wide-gamut/small-gamut images, can I directly use your metadata? Or would it be more advisable for me to gather as much data as I can, and then train and test according to your framework?

2. Could you elaborate on your rationale for selecting 'xy' as an input? As mentioned in your paper, this was partly inspired by Nerf. However, the color matching issue across two dimensions seems to have minimal correlation with the spatial 'x' and 'y'. Have you experimented with adding more layers or employing some shortcut strategies to increase parameters, as an alternative to expanding the number of inputs? I am intrigued by this.

**Comment by hminle** [comment]
Hi @shuwei666 
1. Our GamutMLP framework is optimized per pair of wide-gamut/small-gamut. So it works for a single pair.
2. You could find the ablation study in our supplement material. Without "x,y", the results are much worse. Look at the figure below, which illustrates how clipping works. Some points outside the small gamut get clipped toward the same position. The "x,y" helps to separate those points.
![image](https://github.com/hminle/gamut-mlp/assets/16201681/872b6f32-0ed9-4b71-8b85-77d3024c9481)

**Comment by shuwei666** [comment]
Very clear answer, great research, thanks again!

**Comment by hminle** [comment]
@shuwei666 by the way, we have time and space constraints for our framework, so we want to keep it as lightweight as possible
