### ISSUE TITLE
Training the meta model

### ISSUE THREAD

**Issue by SaraAghajanzadeh** [hminle/gamut-mlp#3]
Hello,

I was wondering how you did the meta training so I can train my own meta model. Did you use a meta learning algorithm like MAML or Reptile? Is it possible to share relevant code?

Thank you.

**Comment by hminle** [comment]
Hi @SaraAghajanzadeh , yes I use those meta learning algorithms.
I just init one MLP and loop through training images, then update MLP's weight after few epochs training per each image.
I already add the code.

Best.
